variable "project" {type = string}
variable "region" {type = string}
variable "sa_dispatcher" {type = string}
variable "sa_dispatcher_tasks" {type = string}
variable "sa_configurator" {type = string}
variable "sa_configurator_tasks" {type = string}
variable "sa_snapshoter_bq" {type = string}
variable "sa_snapshoter_gcs" {type = string}
variable "sa_snapshoter_bq_tasks" {type = string}
variable "sa_snapshoter_gcs_tasks" {type = string}
variable "sa_tagger" {type = string}
variable "sa_tagger_tasks"{type = string}
variable "bq_results_dataset" {type = string}